# @package _global_

# Activate the debug config through the CLI (e.g. `python ... +debug=fast`)

defaults:
  - hydra: inference
  - datamodule: ???
  - model/meta_model: ???
  - trainer: null
  - logger: wandb

  - optional prompting_strategy: null
  - optional local: default.yaml
  - _self_

# path to work directory
work_dir: ${hydra:runtime.cwd}
# path to data directory
data_dir: ${work_dir}/data/
# path to output directory, created dynamically by hydra
output_dir: ${hydra:runtime.output_dir}

ignore_warnings: False
print_config: True

# Seed used to seed everything in the beginning of the run script and to fix randomness in dataset
seed: 123

# determines the log directory's parent folder
logs_subfolder: inference

# experiment name – determines the logging folder's path
run_name: ???
